### ISSUE TITLE
[🐛 Bug]: Ruby example code is not working - Remote WebDriver - Downloads - undefined method `downloadable_files`

### ISSUE THREAD

**Issue by limuyuan** [SeleniumHQ/seleniumhq.github.io#1751]
### What happened?

I'm trying to use Ruby to connect to a remote `WebDriver` and have a zip file downloaded from a [website](https://www.selenium.dev/downloads/).

Here's the official document:
https://www.selenium.dev/documentation/webdriver/drivers/remote_webdriver/
https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/examples/ruby/spec/drivers/remote_webdriver_spec.rb

I'm using Rubymine, and I got the error when trying to run the following line:
```ruby
files = driver.downloadable_files
```
The compiler is showing as the below:
```
Cannot find 'downloadable_files' for type '(Selenium::WebDriver::Remote::Driver | Selenium::WebDriver::Firefox::Driver | Selenium::WebDriver::Safari::Driver | Selenium::WebDriver::IE::Driver | Selenium::WebDriver::Chrome::Driver)' 
```

### What browsers and operating systems are you seeing the problem on?

Windows 11, RubyMine 2024.1.2, selenium-webdriver v4.4.0

**Comment by titusfortner** [comment]
That feature doesn't exist in that version of Selenium. Update to Selenium 4.21 and it should work.

**Comment by limuyuan** [comment]
> That feature doesn't exist in that version of Selenium. Update to Selenium 4.21 and it should work.

Thank you, Titus, it works with 4.21.
